[project]
name = "youtube-downloader"
version = "0.1.0"
description = "Download Youtube video as m4a file."
authors = [
    {name = "Nikita Serditov", email = "serditov.na@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "pytubefix>=8.13.1",
]
